-- Rename legacy auth UID columns
ALTER TABLE "users" RENAME COLUMN "firebaseUid" TO "authUid";
ALTER TABLE "agencies" RENAME COLUMN "firebaseUid" TO "authUid";
ALTER TABLE "admins" RENAME COLUMN "firebaseUid" TO "authUid";

-- Rename unique index names generated by Prisma for legacy columns
ALTER INDEX "users_firebaseUid_key" RENAME TO "users_authUid_key";
ALTER INDEX "agencies_firebaseUid_key" RENAME TO "agencies_authUid_key";
ALTER INDEX "admins_firebaseUid_key" RENAME TO "admins_authUid_key";
